-- Import: makes the Excel price lists the source of truth for Stonewater and
-- Kasper products (124 products, live on rgapricelist.netlify.app as of
-- 2026-10-05; only the typed-in Excel columns are stored, derived prices come
-- from price_catalog). Run after 001_price_tables.sql. Safe to re-run.
--
--   * A product that already exists (same brand + model number, ignoring case
--     and extra spaces) is updated IN PLACE: same id, so its SKUs/barcodes and
--     image stay attached. Name, model, description, price-list group, order,
--     status and prices come from Excel; its product type is kept.
--   * Any other product is inserted with the type listed per row ("type").
--   * Slugs are regenerated as <brand slug>-<model>.
--   * CS-4LM is discontinued; D1000 (not in Excel, no SKUs) is deleted.
--   * Brand "Stonewater Audio" is renamed "Stonewater" (slug unchanged).
--   * No category or barcode prefix is created, changed or deleted.

begin;

update public.brands set name = 'Stonewater' where slug = 'stonewater-audio';

do $import$
declare
  x jsonb; v_id uuid; v_type uuid; n_upd int := 0; n_new int := 0;
  norm constant text := '\s+';
begin
  if not exists (select 1 from public.brands where slug = 'stonewater-audio')
     or not exists (select 1 from public.brands where slug = 'kasper') then
    raise exception 'Brands stonewater-audio and kasper must exist';
  end if;

  for x in select value from jsonb_array_elements($json$[
  {"brand":"stonewater-audio","model":"CS-4LM","description":"20 Watt rms, 4 Inch Dual Cone speaker with LMT","type":"in-ceiling-speakers","category":"Commercial","subcategory":"In Ceiling Speakers","sort_order":10,"status":"discontinued","prices":{"praveen":{"list_price":2145,"dist_incl_tax":1254.34},"distdealer":{"dist_cost":1063,"list_price":1932}}},
  {"brand":"stonewater-audio","model":"CS-6LE","description":"30 Watt rms, 6 Inch 2-way speaker without LMT","type":"in-ceiling-speakers","category":"Commercial","subcategory":"In Ceiling Speakers","sort_order":20,"status":"active","prices":{"praveen":{"list_price":3899,"dist_incl_tax":2015.44},"distdealer":{"dist_cost":1708,"list_price":3105}}},
  {"brand":"stonewater-audio","model":"CS-6LM","description":"30 Watt rms, 6 Inch 2-way speaker with LMT","type":"in-ceiling-speakers","category":"Commercial","subcategory":"In Ceiling Speakers","sort_order":30,"status":"active","prices":{"praveen":{"list_price":4629,"dist_incl_tax":2612.52},"distdealer":{"dist_cost":2214,"list_price":4025}}},
  {"brand":"stonewater-audio","model":"CS-6PP","description":"50 Watt rms, 6\" Fibre glass composite cone speaker, with 2-way crossover, without LMT","type":"in-ceiling-speakers","category":"Commercial","subcategory":"In Ceiling Speakers","sort_order":40,"status":"active","prices":{"praveen":{"list_price":6337,"dist_incl_tax":3694.58},"distdealer":{"dist_cost":3131,"list_price":5693}}},
  {"brand":"stonewater-audio","model":"CS-6KVS","description":"50 Watt rms, 6\" Kevlar Cone speaker, with 2-way crossover, without LMT","type":"in-ceiling-speakers","category":"Commercial","subcategory":"In Ceiling Speakers","sort_order":50,"status":"active","prices":{"praveen":{"list_price":7314,"dist_incl_tax":4253.9},"distdealer":{"dist_cost":3605,"list_price":6555}}},
  {"brand":"stonewater-audio","model":"CS-8PP","description":"100 Watt rms, 8\" Fibre glass composite cone speaker, with 2-way crossover, without LMT","type":"in-ceiling-speakers","category":"Commercial","subcategory":"In Ceiling Speakers","sort_order":60,"status":"active","prices":{"praveen":{"list_price":9258,"dist_incl_tax":5746.6},"distdealer":{"dist_cost":4870,"list_price":8855}}},
  {"brand":"stonewater-audio","model":"QUBE 3","description":"40W, Satellite speaker with 3 Inch Full-Range driver","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":70,"status":"active","prices":{"praveen":{"list_price":3910,"dist_incl_tax":2388.32},"distdealer":{"dist_cost":2024,"list_price":3680}}},
  {"brand":"stonewater-audio","model":"Atom 3","description":"40W, Satellite speaker with 3 Inch Italian Full-Range driver","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":80,"status":"active","prices":{"praveen":{"list_price":7475,"dist_incl_tax":4612.62},"distdealer":{"dist_cost":3909,"list_price":7107}}},
  {"brand":"stonewater-audio","model":"Atom 4","description":"50W, Satellite speaker with 4 Inch Italian Full-Range driver","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":90,"status":"active","prices":{"praveen":{"list_price":8970,"dist_incl_tax":5448.06},"distdealer":{"dist_cost":4617,"list_price":8395}}},
  {"brand":"stonewater-audio","model":"Zeta 3.5","description":"25 Watt rms, 3.5\"  Wall mount Speaker with Tweeter","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":100,"status":"active","prices":{"praveen":{"list_price":5980,"dist_incl_tax":3236.74},"distdealer":{"dist_cost":2743,"list_price":4986}}},
  {"brand":"stonewater-audio","model":"Zeta 3.5T","description":"25 Watt rms, 3.5\"  Wall mount Speaker with Tweeter","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":110,"status":"active","prices":{"praveen":{"list_price":7130,"dist_incl_tax":4220.86},"distdealer":{"dist_cost":3577,"list_price":6502}}},
  {"brand":"stonewater-audio","model":"CURVE 3","description":"20W RMS, 3 Inch 2 Way, Wall mount Speaker with Silk Dome Tweeter","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":120,"status":"active","prices":{"praveen":{"list_price":3795,"dist_incl_tax":2239.64},"distdealer":{"dist_cost":1898,"list_price":3450}}},
  {"brand":"stonewater-audio","model":"CURVE 3T","description":"20W RMS, 3 Inch 2 Way Wall Mount, with LMT","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":130,"status":"active","prices":{"praveen":{"list_price":4198,"dist_incl_tax":2462.66},"distdealer":{"dist_cost":2087,"list_price":3795}}},
  {"brand":"stonewater-audio","model":"Atom 42","description":"100W, Satellite speaker with Dual 4 Inch Italian Full-Range driver","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":140,"status":"active","prices":{"praveen":{"list_price":16330,"dist_incl_tax":9926.16},"distdealer":{"dist_cost":8412,"list_price":15295}}},
  {"brand":"stonewater-audio","model":"ELEMENT 5 N","description":"40W, 5.25 Inch Wall mount Speaker with tweeter","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":150,"status":"active","prices":{"praveen":{"list_price":14375,"dist_incl_tax":8732},"distdealer":{"dist_cost":7400,"list_price":13455}}},
  {"brand":"stonewater-audio","model":"ELEMENT 5T N","description":"40W, 5.25 Inch, LMT Wall mount Speaker with tweeter","type":"wall-mount-speakers","category":"Commercial","subcategory":"Wall Mount Speakers","sort_order":160,"status":"active","prices":{"praveen":{"list_price":16445,"dist_incl_tax":10374.56},"distdealer":{"dist_cost":8792,"list_price":15985}}},
  {"brand":"stonewater-audio","model":"PT-4","description":"40W waterproof pendant hanging speaker with tweeter","type":"pendant-speakers","category":"Commercial","subcategory":"Pendant Speakers","sort_order":170,"status":"active","prices":{"praveen":{"list_price":12650,"dist_incl_tax":7568.52},"distdealer":{"dist_cost":6414,"list_price":11661}}},
  {"brand":"stonewater-audio","model":"PT-5","description":"50W waterproof pendant hanging speaker with tweeter","type":"pendant-speakers","category":"Commercial","subcategory":"Pendant Speakers","sort_order":180,"status":"active","prices":{"praveen":{"list_price":14720,"dist_incl_tax":8314.28},"distdealer":{"dist_cost":7046,"list_price":12811}}},
  {"brand":"stonewater-audio","model":"QUBE SUB 8","description":"200W, 8 Inch Passive Subwoofer","type":"commercial-subwoofer","category":"Commercial","subcategory":"SUBWOOFERS","sort_order":190,"status":"active","prices":{"praveen":{"list_price":12880,"dist_incl_tax":7463.5},"distdealer":{"dist_cost":6325,"list_price":11500}}},
  {"brand":"stonewater-audio","model":"ATOMSUB10","description":"400W, 10 Inch Passive Subwoofer","type":"commercial-subwoofer","category":"Commercial","subcategory":"SUBWOOFERS","sort_order":200,"status":"active","prices":{"praveen":{"list_price":28175,"dist_incl_tax":16419.7},"distdealer":{"dist_cost":13915,"list_price":25300}}},
  {"brand":"stonewater-audio","model":"IMPULSE 150","description":"250W, 12 Inch Passive Subwoofer","type":"commercial-subwoofer","category":"Commercial","subcategory":"SUBWOOFERS","sort_order":210,"status":"active","prices":{"praveen":{"list_price":26220,"dist_incl_tax":14837.32},"distdealer":{"dist_cost":12574,"list_price":22862}}},
  {"brand":"stonewater-audio","model":"IMPULSE 300A","description":"300W, 12 Inch Powered Subwoofer","type":"commercial-subwoofer","category":"Commercial","subcategory":"SUBWOOFERS","sort_order":220,"status":"active","prices":{"praveen":{"list_price":55200,"dist_incl_tax":34332.1},"distdealer":{"dist_cost":29095,"list_price":52900}}},
  {"brand":"stonewater-audio","model":"ZONE8","description":"8 Zone Amplifier with sub line out - USB input, 25W @ 4 Ohms","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":230,"status":"active","prices":{"praveen":{"list_price":29095,"dist_incl_tax":16271.02},"distdealer":{"dist_cost":13789,"list_price":25070}}},
  {"brand":"stonewater-audio","model":"SR200","description":"2.1 Ch Amplifier, 200W @ 4 Ohms","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":240,"status":"active","prices":{"praveen":{"list_price":30475,"dist_incl_tax":18285.28},"distdealer":{"dist_cost":15496,"list_price":28175}}},
  {"brand":"stonewater-audio","model":"SA302","description":"Stero Amplifer 70Wx2 @ 4 Ohms","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":250,"status":"active","prices":{"praveen":{"list_price":24380,"dist_incl_tax":14849.12},"distdealer":{"dist_cost":12584,"list_price":22880}}},
  {"brand":"stonewater-audio","model":"QUBE AMP","description":"2.1 Ch Amplifier, 120W @ 4 Ohms","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":260,"status":"active","prices":{"praveen":{"list_price":17825,"dist_incl_tax":11254.84},"distdealer":{"dist_cost":9538,"list_price":17342}}},
  {"brand":"stonewater-audio","model":"Zone4","description":"4 Zone Amplifier with sub line out - USB input, 55W @ 4 Ohms","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":270,"status":"active","prices":{"praveen":{"list_price":29095,"dist_incl_tax":15673.94},"distdealer":{"dist_cost":13283,"list_price":24150}}},
  {"brand":"stonewater-audio","model":"DD500","description":"250W x 2 direct drive 100v line power amplifier","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":280,"status":"active","prices":{"praveen":{"list_price":31878,"dist_incl_tax":18808.02},"distdealer":{"dist_cost":15939,"list_price":28980}}},
  {"brand":"stonewater-audio","model":"SMX60","description":"60W 100V Amplifier","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":290,"status":"active","prices":{"praveen":{"list_price":18975,"dist_incl_tax":12165.8},"distdealer":{"dist_cost":10310,"list_price":18745}}},
  {"brand":"stonewater-audio","model":"SMX120","description":"120W 100V Amplifier","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":300,"status":"active","prices":{"praveen":{"list_price":28405,"dist_incl_tax":17553.68},"distdealer":{"dist_cost":14876,"list_price":27048}}},
  {"brand":"stonewater-audio","model":"SMX240","description":"240W 100V Amplifier","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":310,"status":"active","prices":{"praveen":{"list_price":39790,"dist_incl_tax":25256.72},"distdealer":{"dist_cost":21404,"list_price":38916}}},
  {"brand":"stonewater-audio","model":"4Z360","description":"90Wx4 zone/360W 100V line amplifier","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":320,"status":"active","prices":{"praveen":{"list_price":48415,"dist_incl_tax":29705.32},"distdealer":{"dist_cost":25174,"list_price":45770}}},
  {"brand":"stonewater-audio","model":"DX3i","description":"2.1 Channel DSP Based Amplifier","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":330,"status":"active","prices":{"praveen":{"list_price":110975,"dist_incl_tax":77918.94},"distdealer":{"dist_cost":66033,"list_price":120060}}},
  {"brand":"stonewater-audio","model":"SW100","description":"Subwoofer amplifier","type":"commercial-amplifiers","category":"Commercial","subcategory":"Amplifiers","sort_order":340,"status":"active","prices":{"praveen":{"list_price":15180,"dist_incl_tax":9404.6},"distdealer":{"dist_cost":7970,"list_price":14490}}},
  {"brand":"stonewater-audio","model":"MIX12","description":"Line Mixer","type":"commercial-amplifiers","category":"Commercial","subcategory":"Line Mixer","sort_order":350,"status":"active","prices":{"praveen":{"list_price":15525,"dist_incl_tax":7788},"distdealer":{"dist_cost":7590,"list_price":13800}}},
  {"brand":"stonewater-audio","model":"Media Pro","description":"Media Player with MP3/WMA/FLAC/WAV music format","type":"media-player","category":"Commercial","subcategory":"Media Player","sort_order":360,"status":"active","prices":{"praveen":{"list_price":17500,"dist_incl_tax":11617.1},"distdealer":{"dist_cost":9845,"list_price":17900}}},
  {"brand":"stonewater-audio","model":"Media Player MP-01","description":"Media Player with BT 5.0 and FM capabilities","type":"media-player","category":"Commercial","subcategory":"Media Player","sort_order":370,"status":"active","prices":{"praveen":{"list_price":8000,"dist_incl_tax":4673},"distdealer":{"dist_cost":3960,"list_price":7200}}},
  {"brand":"stonewater-audio","model":"SW01","description":"Wifi Streamer with BT 5.0 and Network","type":"media-player","category":"Commercial","subcategory":"Streamer","sort_order":380,"status":"active","prices":{"praveen":{"list_price":14960,"dist_incl_tax":8826.4},"distdealer":{"dist_cost":7480,"list_price":13600}}},
  {"brand":"stonewater-audio","model":"MICRO 6 Italian","description":"100W, 6 Inch 2 Way","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Medium Power Systems","sort_order":390,"status":"active","prices":{"praveen":{"list_price":31246,"dist_incl_tax":18859.94},"distdealer":{"dist_cost":15983,"list_price":29061}}},
  {"brand":"stonewater-audio","model":"MICROSUB12","description":"400W, 12 Inch Bandpass Subwoofer","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"Medium Power Systems","sort_order":400,"status":"active","prices":{"praveen":{"list_price":44873,"dist_incl_tax":27090.44},"distdealer":{"dist_cost":22958,"list_price":41743}}},
  {"brand":"stonewater-audio","model":"RZ8","description":"250W, 8 Inch, 2 Way Top, Fly Ready","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Rezolution Series","sort_order":410,"status":"active","prices":{"praveen":{"list_price":35360,"dist_incl_tax":21345.61},"distdealer":{"dist_cost":18089.5,"list_price":32890}}},
  {"brand":"stonewater-audio","model":"RZ12","description":"400W, 12 Inch, 2 Way Top, fly ready","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Rezolution Series","sort_order":420,"status":"active","prices":{"praveen":{"list_price":50730,"dist_incl_tax":30626.31},"distdealer":{"dist_cost":25954.5,"list_price":47190}}},
  {"brand":"stonewater-audio","model":"RZ15","description":"500W, 15 Inch, 2 Way Top, fly ready","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Rezolution Series","sort_order":430,"status":"active","prices":{"praveen":{"list_price":62140,"dist_incl_tax":37512.2},"distdealer":{"dist_cost":31790,"list_price":57800}}},
  {"brand":"stonewater-audio","model":"RZ118","description":"1000W, Single 18 Subwoofer","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"Rezolution Series","sort_order":440,"status":"active","prices":{"praveen":{"list_price":69180,"dist_incl_tax":41763.15},"distdealer":{"dist_cost":35392.5,"list_price":64350}}},
  {"brand":"stonewater-audio","model":"RZ218","description":"2000W, Dual 18 Subwoofer","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"Rezolution Series","sort_order":450,"status":"active","prices":{"praveen":{"list_price":122980,"dist_incl_tax":74245.6},"distdealer":{"dist_cost":62920,"list_price":114400}}},
  {"brand":"stonewater-audio","model":"HD8","description":"250W, 8 Inch, 2 Way Top, Fly Ready","type":"professional-speakers","category":"PRO AUDIO","subcategory":"HD Series","sort_order":460,"status":"active","prices":{"praveen":{"list_price":57380,"dist_incl_tax":34643.62},"distdealer":{"dist_cost":29359,"list_price":53380}}},
  {"brand":"stonewater-audio","model":"HD12","description":"500W, 12 Inch, 2 Way Top, fly ready","type":"professional-speakers","category":"PRO AUDIO","subcategory":"HD Series","sort_order":470,"status":"active","prices":{"praveen":{"list_price":76760,"dist_incl_tax":46338.6},"distdealer":{"dist_cost":39270,"list_price":71400}}},
  {"brand":"stonewater-audio","model":"HD15","description":"800W, 15 Inch, 2 Way Top, fly ready","type":"professional-speakers","category":"PRO AUDIO","subcategory":"HD Series","sort_order":480,"status":"active","prices":{"praveen":{"list_price":98870,"dist_incl_tax":59688.53},"distdealer":{"dist_cost":50583.5,"list_price":91970}}},
  {"brand":"stonewater-audio","model":"HD118","description":"1800W, Single 18 Subwoofer","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"HD Series","sort_order":490,"status":"active","prices":{"praveen":{"list_price":91380,"dist_incl_tax":55165},"distdealer":{"dist_cost":46750,"list_price":85000}}},
  {"brand":"stonewater-audio","model":"HD218","description":"3600W, Single 18 Subwoofer","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"HD Series","sort_order":500,"status":"active","prices":{"praveen":{"list_price":164480,"dist_incl_tax":99297},"distdealer":{"dist_cost":84150,"list_price":153000}}},
  {"brand":"stonewater-audio","model":"AQUA 6","description":"6 Inch, 2-Way, IP Rated Top","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Aqua Series - IP Rated","sort_order":510,"status":"active","prices":{"praveen":{"list_price":26807,"dist_incl_tax":16183.7},"distdealer":{"dist_cost":13715,"list_price":24937}}},
  {"brand":"stonewater-audio","model":"AQUA 8","description":"8 Inch, 2-Way, IP Rated Top","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Aqua Series - IP Rated","sort_order":520,"status":"active","prices":{"praveen":{"list_price":35524,"dist_incl_tax":21448.86},"distdealer":{"dist_cost":18177,"list_price":33049}}},
  {"brand":"stonewater-audio","model":"Aqua 12","description":"12 Inch, 2-Way, IP Rated Top","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Aqua Series - IP Rated","sort_order":530,"status":"active","prices":{"praveen":{"list_price":76153,"dist_incl_tax":45975.16},"distdealer":{"dist_cost":38962,"list_price":70840}}},
  {"brand":"stonewater-audio","model":"SUB18C","description":"1000W, 18 Inch Subwoofer, Weather Proof","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"Aqua Series - IP Rated","sort_order":540,"status":"active","prices":{"praveen":{"list_price":121110,"dist_incl_tax":73118.94},"distdealer":{"dist_cost":61965.2,"list_price":112664}}},
  {"brand":"stonewater-audio","model":"DX3","description":"600W+600W+1500W @ 4 Ohms, 3CH Amplifier with DSP","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":550,"status":"active","prices":{"praveen":{"list_price":112230,"dist_incl_tax":67755.6},"distdealer":{"dist_cost":57420,"list_price":104400}}},
  {"brand":"stonewater-audio","model":"M1000","description":"1000W + 1000W @ 4 Ohms, 2 Ch, Power Amp, THD: 0.02%","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":560,"status":"active","prices":{"praveen":{"list_price":57300,"dist_incl_tax":34591.7},"distdealer":{"dist_cost":29315,"list_price":53300}}},
  {"brand":"stonewater-audio","model":"M1400","description":"1400W + 1400W @ 4 Ohms, 2 Ch, Power Amp, THD: 0.02%","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":570,"status":"active","prices":{"praveen":{"list_price":64720,"dist_incl_tax":39069.8},"distdealer":{"dist_cost":33110,"list_price":60200}}},
  {"brand":"stonewater-audio","model":"M1700","description":"1700W + 1700W @ 4 Ohms, 2 Ch, Power Amp, THD: 0.02%","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":580,"status":"active","prices":{"praveen":{"list_price":75470,"dist_incl_tax":45559.8},"distdealer":{"dist_cost":38610,"list_price":70200}}},
  {"brand":"stonewater-audio","model":"4M600","description":"4 x 600W @ 4 OHMS, 4 Ch, Power Amp, THD: 0.02%","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":590,"status":"active","prices":{"praveen":{"list_price":87080,"dist_incl_tax":52569},"distdealer":{"dist_cost":44550,"list_price":81000}}},
  {"brand":"stonewater-audio","model":"B 4.2","description":"1150W x 4 @ 4 ohms, 4 CH BASS Amplifier","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":600,"status":"active","prices":{"praveen":{"list_price":86430,"dist_incl_tax":52179.6},"distdealer":{"dist_cost":44220,"list_price":80400}}},
  {"brand":"stonewater-audio","model":"B 4.25","description":"1800W x 4 @ 4 ohms, 4 CH BASS Amplifier","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":610,"status":"active","prices":{"praveen":{"list_price":110730,"dist_incl_tax":66847},"distdealer":{"dist_cost":56650,"list_price":103000}}},
  {"brand":"stonewater-audio","model":"B 4.3","description":"3650W x 4 @ 4 ohms, 4 CH BASS Amplifier","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"Amplifiers","sort_order":620,"status":"active","prices":{"praveen":{"list_price":276280,"dist_incl_tax":166793},"distdealer":{"dist_cost":141350,"list_price":257000}}},
  {"brand":"stonewater-audio","model":"P800","description":"800W, Dual 12, 3 way Point Source","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Touring Sytems","sort_order":630,"status":"active","prices":{"praveen":{"list_price":272300,"dist_incl_tax":164391.7},"distdealer":{"dist_cost":139315,"list_price":253300}}},
  {"brand":"stonewater-audio","model":"PXB218","description":"2000W, Dual 18 Hybrid Subwoofer","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"Touring Sytems","sort_order":640,"status":"active","prices":{"praveen":{"list_price":193500,"dist_incl_tax":116820},"distdealer":{"dist_cost":99000,"list_price":180000}}},
  {"brand":"stonewater-audio","model":"IFR3600","description":"3600W, Dual 18 INFRA SUBWOOFER","type":"professional-subwoofer","category":"PRO AUDIO","subcategory":"Touring Sytems","sort_order":650,"status":"active","prices":{"praveen":{"list_price":269610,"dist_incl_tax":162769.2},"distdealer":{"dist_cost":137940,"list_price":250800}}},
  {"brand":"stonewater-audio","model":"DC48","description":"Speaker Management system","type":"professional-amplifier","category":"PRO AUDIO","subcategory":"SPEAKER Management System","sort_order":660,"status":"active","prices":{"praveen":{"list_price":99920,"dist_incl_tax":60324.55},"distdealer":{"dist_cost":51122.5,"list_price":92950}}},
  {"brand":"stonewater-audio","model":"Line 36","description":"120W RMS, 6 precisely positioned 3 Inch, Italian made high fidelity transducers.","type":"professional-speakers","category":"PRO AUDIO","subcategory":"Line Speakers","sort_order":670,"status":"active","prices":{"praveen":{"list_price":24035,"dist_incl_tax":14182},"distdealer":{"dist_cost":12018,"list_price":21850}}},
  {"brand":"kasper","model":"KMA-8120","description":"120W Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":10,"status":"active","prices":{"kasper":{"mrp":33900}}},
  {"brand":"kasper","model":"KMA-8240","description":"240W Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":20,"status":"active","prices":{"kasper":{"mrp":41900}}},
  {"brand":"kasper","model":"KMA-8360","description":"350W Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":30,"status":"active","prices":{"kasper":{"mrp":52900}}},
  {"brand":"kasper","model":"KMA-8500","description":"500W Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":40,"status":"active","prices":{"kasper":{"mrp":63900}}},
  {"brand":"kasper","model":"KMA-8120-Z5","description":"120W 5 Zone Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":50,"status":"active","prices":{"kasper":{"mrp":38900}}},
  {"brand":"kasper","model":"KMA-8240-Z5","description":"240W 5 Zone Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":60,"status":"active","prices":{"kasper":{"mrp":49900}}},
  {"brand":"kasper","model":"KMA-8360-Z5","description":"350W 5 Zone Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":70,"status":"active","prices":{"kasper":{"mrp":57900}}},
  {"brand":"kasper","model":"KMA-8500-Z5","description":"500W 5 Zone Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":80,"status":"active","prices":{"kasper":{"mrp":68900}}},
  {"brand":"kasper","model":"KMA-8650-Z5","description":"650W 5 Zone Mixer Amplifier with MP3/FM Tuner/Bluetooth","type":"commercial-amplifiers","category":"","subcategory":"MIXER AMPLIFIER","sort_order":90,"status":"active","prices":{"kasper":{"mrp":78900}}},
  {"brand":"kasper","model":"KZMA-4100L","description":"4 Channel Digital Power Amplifier 100W at 8Ohm with Bluetooth 5.0, USB interface, FM Radio, Support lossless format music playback Two microphone interfaces, anti-howling 2 stereo channels, 4 zones, Support remote control","type":"commercial-amplifiers","category":"","subcategory":"ZONE AMPLIFIER","sort_order":100,"status":"active","prices":{"kasper":{"mrp":36900}}},
  {"brand":"kasper","model":"KZMA-8050L","description":"8 channel constant resistance amplifier 50W at 8Ohm 4 stereo channels, Support lossless format music play, Support Bluetooth 5.0, FM radio, One Audio out, Two AUX input ,Support USB port, Support voice prompt tone, Support High and low pitch adjustment","type":"commercial-amplifiers","category":"","subcategory":"ZONE AMPLIFIER","sort_order":110,"status":"active","prices":{"kasper":{"mrp":48900}}},
  {"brand":"kasper","model":"D-2350","description":"2Channel Power Amplifier 350W / Class D-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":120,"status":"active","prices":{"kasper":{"mrp":36900}}},
  {"brand":"kasper","model":"D-4350","description":"4 Channel Power Amplifier 350W / Class D-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":130,"status":"active","prices":{"kasper":{"mrp":49900}}},
  {"brand":"kasper","model":"D-2600.2","description":"2 Channel Power Amplifier 600W / Class D-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":140,"status":"active","prices":{"kasper":{"mrp":48900}}},
  {"brand":"kasper","model":"D-4600.2","description":"4 Channel Power Amplifier 600W / Class D-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":150,"status":"active","prices":{"kasper":{"mrp":69900}}},
  {"brand":"kasper","model":"H-4400A","description":"4 Channel Power Amplifier 400W / Class H-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":160,"status":"active","prices":{"kasper":{"mrp":96900}}},
  {"brand":"kasper","model":"HP-21000C","description":"2 Channel Power Amplifier 1000W / Class H-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":170,"status":"active","prices":{"kasper":{"mrp":99900}}},
  {"brand":"kasper","model":"H-4600A","description":"4 Channel Power Amplifier 600W / Class H-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":180,"status":"active","prices":{"kasper":{"mrp":109900}}},
  {"brand":"kasper","model":"HP-21500C","description":"MIXER AMPLIFIER - SINGLE ZONE 2 Channel Power Amplifier 1500W / Class H-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":190,"status":"active","prices":{"kasper":{"mrp":129900}}},
  {"brand":"kasper","model":"H-41000C 2U","description":"4 Channel Power Amplifier 1000W / Class H-Amplifier","type":"professional-amplifier","category":"","subcategory":"KREST SERIES - POWER AMPLIFIER","sort_order":200,"status":"active","prices":{"kasper":{"mrp":134900}}},
  {"brand":"kasper","model":"KSP-A36","description":"3 In 6 out DSP Audio Processor High-performance digital DSP processor that supports multi-channel analog signal routing supporting 64-bit floating-point optimized FIR and IIR algorithms; the A/D part uses the AK5552 analog-to-digital conversion chip Frequency response (20Hz-20kHz@+4dBu): +0/-0.3dB Total harmonic distortion (20Hz-20kHz@+4dBu): <0.003%","type":"professional-amplifier","category":"","subcategory":"DIGITAL SIGNAL PROCESSOR","sort_order":210,"status":"active","prices":{"kasper":{"mrp":54900}}},
  {"brand":"kasper","model":"KSP-A48.2","description":"4 In 8 out DSP Audio Processor High-performance digital DSP processor that supports multi-channel analog signal routing supporting 64-bit floating-point optimized FIR and IIR algorithms; the A/D part uses the AK5552 analog-to-digital conversion chip Frequency response (20Hz-20kHz@+4dBu): +0/-0.3dB Total harmonic distortion (20Hz-20kHz@+4dBu): <0.003%","type":"professional-amplifier","category":"","subcategory":"DIGITAL SIGNAL PROCESSOR","sort_order":220,"status":"active","prices":{"kasper":{"mrp":59900}}},
  {"brand":"kasper","model":"KSP-S36","description":"3in 6out Full Display DSP Audio Processor routing supporting 64-bit floating-point optimized FIR and IIR algorithms; the A/D part uses the AK5552 analog-to-digital conversion chip Input channels: 4ch analog XLR balanced Output channels: 8ch analog XLR balanced Frequency response (20Hz-20kHz@+4dBu): +0/-0.3dB Total harmonic distortion (20Hz-20kHz@+4dBu): <0.003%","type":"professional-amplifier","category":"","subcategory":"DIGITAL SIGNAL PROCESSOR","sort_order":230,"status":"active","prices":{"kasper":{"mrp":65900}}},
  {"brand":"kasper","model":"KSP-S48.2","description":"4in 8 out Full Display DSP Audio Processor High-performance digital DSP processor that supports multi-channel analog signal routing supporting 64-bit floating-point optimized FIR and IIR algorithms; the A/D part uses the AK5552 analog-to-digital conversion chip Input channels: 4ch analog XLR balanced Output channels: 8ch analog XLR balanced Frequency response (20Hz-20kHz@+4dBu): +0/-0.3dB Total harmonic distortion (20Hz-20kHz@+4dBu): <0.003%","type":"professional-amplifier","category":"","subcategory":"DIGITAL SIGNAL PROCESSOR","sort_order":240,"status":"active","prices":{"kasper":{"mrp":72900}}},
  {"brand":"kasper","model":"Avalon X520","description":"Kasper 5.2 Channel AVR Output- 4-8 Ohm Total Output Power - 500W SNR - >=75dB THD - less than 0.5% at 1Khz","type":"cinema-amplifier","category":"","subcategory":"AVALON AVR- 8K","sort_order":250,"status":"active","prices":{"kasper":{"mrp":49900}}},
  {"brand":"kasper","model":"Ênte 10","description":"-Stream music from your phone over WiFi, AirPlay, Spotify Connect, and Bluetooth 5.0. - Rich Interfaces: Optical Out, Line In/Out, Type-C DAC input, Lan, USB Host. - HD Sound: Support CD quality high-definition sound streaming. - Support Spotify, Amazon Music, Tidal, Qobuz, TuneIn, Internet Radio and more. - Multiroom: Sync music or play different songs across all rooms. -Outlook: New OLED mode display and touch button with friendly use. -Spdif Out: New optical output for HQ audio transmit. -Type-C Port: New type-c port for 5V1A power supply and PC digital audio input.","type":"media-player","category":"","subcategory":"ÊNTE SERIES","sort_order":260,"status":"active","prices":{"kasper":{"mrp":15900}}},
  {"brand":"kasper","model":"Ênte 50","description":"-Add Wireless Capability To Your Home Audio System: Add WiFi, Direct Streaming, Airplay, Spotify Connect and Aptx HD Bluetooth 5.0 -Multiroom Audio System -Extraordinary Sound Performance: Ênte 50 uses the famous ESS Sabre 9023 DAC and supports Aptx HD Bluetooth 5.0.","type":"media-player","category":"","subcategory":"ÊNTE SERIES","sort_order":270,"status":"active","prices":{"kasper":{"mrp":33900}}},
  {"brand":"kasper","model":"Ênte 50A","description":"-Add Wireless Capability To Your Home Audio System: Add WiFi, AirPlay, Spotify Connect and Bluetooth 5.0 wireless capability to your passive speakers, and active Connect your existing amplifiers, preamps and recievers via optical and RCA Line in, or your computer audio via the Micro-USB port. -Multiroom Audio System. -Powerful Stereo Amplifier. Brilliant Sound Streamed Directly From Your Favorite Providers: Spotify, Amazon Music, Tidal, Qobuz, Deezer, Napster, TuneIn, Internet Radio, iHeart Radio, QQ Music, QQ FM.","type":"media-player","category":"","subcategory":"ÊNTE SERIES","sort_order":280,"status":"active","prices":{"kasper":{"mrp":39900}}},
  {"brand":"kasper","model":"Ênte 80A","description":"-Home Theater 80Wx2 High-Res Wireless Stereo Audio Amplifier can use Airplay2 to stream music from your iOS device. It has WiFi and bluetooth 5.0 and support multiroom music streaming '-Music Sources: Spotify Connect,Tidal Connect,Airplay 2, DLNA,UPnP,Qplay '-Spotify, Deezer, TuneIn, Tidal, Qobuz, Napster, iHeartRadio, more coming in the near future Local storage: Music stored on the mobile device memory, NAS, USB pen drive Multizone Function: 1.By 4stream APP to set up one device sa master to sync music to other connected devices 2.By Airplay2 multiroom function","type":"media-player","category":"","subcategory":"ÊNTE SERIES","sort_order":290,"status":"active","prices":{"kasper":{"mrp":46900}}},
  {"brand":"kasper","model":"KCS-N508T","description":"Power at 100V - 3/6W Power at 70V - 1.5/3W SPL( 1W/1M) - 92dB, Freq. Response - 100Hz- 16KHz Cutout Size - Dia 150mm Installation - Inceiling Enclosure Material - ABS Weight - 0.5Kg Finish - White. Product Size - Dia175x60mm(H) Max SPL@ 1M - 99dB. Speakers - 5\"x1 full range","type":"in-ceiling-speakers","category":"","subcategory":"IN-CEILING FRAMELESS SPEAKERS","sort_order":300,"status":"active","prices":{"kasper":{"mrp":2490}}},
  {"brand":"kasper","model":"KCS-E608T **Coming Soon","description":"MIXER AMPLIFIER - SINGLE ZONE 6inch ceiling speaker 70-110v with transformer Rated Power: 3-15W, Peak Power: 30W, Impedence:8Ω, Dimenssions: 226 * 85mm","type":"in-ceiling-speakers","category":"","subcategory":"IN-CEILING FRAMELESS SPEAKERS","sort_order":310,"status":"active","prices":{"kasper":{"mrp":1770}}},
  {"brand":"kasper","model":"KCS-N608T","description":"Power at 100V - 3/6W Power at 70V - 1.5/3W SPL( 1W/1M) - 92dB. Freq. Response - 100Hz- 18KHz Cutout Size - Dia 170mm Installation - Inceiling Enclosure Material - ABS Weight - 0.7Kg.Product Size - Dia175x60mm(H) Max SPL@ 1M - 99dB. Speakers - 6\"x1 full range","type":"in-ceiling-speakers","category":"","subcategory":"IN-CEILING FRAMELESS SPEAKERS","sort_order":320,"status":"active","prices":{"kasper":{"mrp":3490}}},
  {"brand":"kasper","model":"KCS-N808T","description":"Power at 100V - 5/10W Power at 70V - 2.5/5W SPL( 1W/1M) - 92dB.Freq. Response - 100Hz- 18KHz Cutout Size - Dia 210mm Installation - Inceiling Enclosure Material - ABS Weight - 0.7Kg. Product Size - Dia 230x90mm(H) Max SPL@ 1M - 101dB.Speakers - 8\"x1 full range","type":"in-ceiling-speakers","category":"","subcategory":"IN-CEILING FRAMELESS SPEAKERS","sort_order":330,"status":"active","prices":{"kasper":{"mrp":5990}}},
  {"brand":"kasper","model":"KCS-R624","description":"Power at 15W /8 ohms SPL( 1W/1M) - 89dB Max SPL@ 1M - 101dB Freq. Response - 65Hz-20KHz Cutout Size - Dia 170mm Speakers - Inceiling Enclosure Material - ABS Weight - 0.8KG Finish - White Installation - Dia 187x80mm(H) Product Size - 1\" x1 (TREBLE) 6\"x1(BASS)","type":"in-ceiling-speakers","category":"","subcategory":"IN-CEILING FRAMELESS SPEAKERS","sort_order":340,"status":"active","prices":{"kasper":{"mrp":5290}}},
  {"brand":"kasper","model":"KCS-R628T","description":"Power at 100V /8 ohms - 15W /7.5W SPL( 1W/1M) - 89dB Max SPL@ 1M - 101dB Freq. Response - 65Hz-20KHz Cutout Size - Dia 170mm Speakers - Inceiling Enclosure Material - ABS Weight - 1.0KG Finish - White Installation - Dia 187x87mm(H) Product Size - 1\" x1 (TREBLE) 6\"x1(BASS)","type":"in-ceiling-speakers","category":"","subcategory":"IN-CEILING FRAMELESS SPEAKERS","sort_order":350,"status":"active","prices":{"kasper":{"mrp":5790}}},
  {"brand":"kasper","model":"KSM-620T","description":"5.5inch surface ceiling speaker with 5W/10W/20W/30W Input:70-100V Frequency","type":"wall-mount-speakers","category":"","subcategory":"SURFACE MOUNT SPEAKER","sort_order":360,"status":"active","prices":{"kasper":{"mrp":5790}}},
  {"brand":"kasper","model":"GPW530","description":"5\" 30W Indoor/Outdoor IP66 Waterproof Speaker (With pendant and ground stand installation kits)","type":"commercial-speakers","category":"","subcategory":"WEATHERPROOF OUTDOOR SPEAKER","sort_order":370,"status":"active","prices":{"kasper":{"mrp":21900}}},
  {"brand":"kasper","model":"GPW640","description":"6.5\" 40W Indoor/Outdoor IP66 Waterproof Speaker (With pendant and ground stand installation kits)","type":"commercial-speakers","category":"","subcategory":"WEATHERPROOF OUTDOOR SPEAKER","sort_order":380,"status":"active","prices":{"kasper":{"mrp":24900}}},
  {"brand":"kasper","model":"GPW530-BE (Upon request)","description":"5\" 30W Indoor/Outdoor IP66 Waterproof Speaker (With pendant and ground stand installation kits)","type":"commercial-speakers","category":"","subcategory":"WEATHERPROOF OUTDOOR SPEAKER","sort_order":390,"status":"active","prices":{"kasper":{"mrp":24900}}},
  {"brand":"kasper","model":"KLA-D84","description":"DUAL 8'' INCHES /400W, Power","type":"professional-speakers","category":"","subcategory":"INKLINE - LINE ARRAYS","sort_order":400,"status":"active","prices":{"kasper":{"mrp":113990}}},
  {"brand":"kasper","model":"KLA-D106","description":"MIXER AMPLIFIER - SINGLE ZONE DUAL 10'' INCHES/600W'","type":"professional-speakers","category":"","subcategory":"INKLINE - LINE ARRAYS","sort_order":410,"status":"active","prices":{"kasper":{"mrp":160990}}},
  {"brand":"kasper","model":"KLA-D1212","description":"DUAL 12'' INCHES /1200W","type":"professional-speakers","category":"","subcategory":"INKLINE - LINE ARRAYS","sort_order":420,"status":"active","prices":{"kasper":{"mrp":213990}}},
  {"brand":"kasper","model":"KLOUT-208","description":"8'' INCHES SINGLE /200W","type":"professional-speakers","category":"","subcategory":"POINT SOURCE SPEAKERS","sort_order":430,"status":"active","prices":{"kasper":{"mrp":27990}}},
  {"brand":"kasper","model":"KLOUT-312","description":"12'' INCHES SINGLE /300W","type":"professional-speakers","category":"","subcategory":"POINT SOURCE SPEAKERS","sort_order":440,"status":"active","prices":{"kasper":{"mrp":62990}}},
  {"brand":"kasper","model":"KLOUT-415","description":"15' 'INCHES SINGLE /400W","type":"professional-speakers","category":"","subcategory":"POINT SOURCE SPEAKERS","sort_order":450,"status":"active","prices":{"kasper":{"mrp":72990}}},
  {"brand":"kasper","model":"KMON-412","description":"12'' INCHES SINGLE /400W","type":"professional-speakers","category":"","subcategory":"MONITOR SPEAKERS","sort_order":460,"status":"active","prices":{"kasper":{"mrp":66990}}},
  {"brand":"kasper","model":"KMON-415","description":"15' 'INCHES SINGLE /400W","type":"professional-speakers","category":"","subcategory":"MONITOR SPEAKERS","sort_order":470,"status":"active","prices":{"kasper":{"mrp":84990}}},
  {"brand":"kasper","model":"PS- 12S40","description":"12' INCHES SINGLE /400W","type":"professional-subwoofer","category":"","subcategory":"KUA - SUBWOOFERS","sort_order":480,"status":"active","prices":{"kasper":{"mrp":68900}}},
  {"brand":"kasper","model":"PS - 15S8","description":"15' INCHES SINGLE /800W","type":"professional-subwoofer","category":"","subcategory":"KUA - SUBWOOFERS","sort_order":490,"status":"active","prices":{"kasper":{"mrp":76990}}},
  {"brand":"kasper","model":"PS - 18S10","description":"18' INCHES SINGLE /1000W","type":"professional-subwoofer","category":"","subcategory":"KUA - SUBWOOFERS","sort_order":500,"status":"active","prices":{"kasper":{"mrp":99990}}},
  {"brand":"kasper","model":"PS - 15D16","description":"15' INCHES DUAL /1600W","type":"professional-subwoofer","category":"","subcategory":"KUA - SUBWOOFERS","sort_order":510,"status":"active","prices":{"kasper":{"mrp":128990}}},
  {"brand":"kasper","model":"PS - 18D20","description":"18' INCHES DUAL /2000W","type":"professional-subwoofer","category":"","subcategory":"KUA - SUBWOOFERS","sort_order":520,"status":"active","prices":{"kasper":{"mrp":174990}}},
  {"brand":"kasper","model":"PS-12S40 OD","description":"12' INCHES SINGLE /400W","type":"professional-subwoofer","category":"","subcategory":"KUA - OUTDOOR SUBWOOFERS","sort_order":530,"status":"active","prices":{"kasper":{"mrp":99990}}},
  {"brand":"kasper","model":"PS - 15S8 OD","description":"15' INCHES SINGLE /800W","type":"professional-subwoofer","category":"","subcategory":"KUA - OUTDOOR SUBWOOFERS","sort_order":540,"status":"active","prices":{"kasper":{"mrp":135990}}},
  {"brand":"kasper","model":"PS - 18S10 OD","description":"MIXER AMPLIFIER - SINGLE ZONE 18' INCHES SINGLE /1,400W","type":"professional-subwoofer","category":"","subcategory":"KUA - OUTDOOR SUBWOOFERS","sort_order":550,"status":"active","prices":{"kasper":{"mrp":157990}}},
  {"brand":"kasper","model":"PS - 15D16 OD","description":"15' INCHES DUAL /1600W","type":"professional-subwoofer","category":"","subcategory":"KUA - OUTDOOR SUBWOOFERS","sort_order":560,"status":"active","prices":{"kasper":{"mrp":245990}}},
  {"brand":"kasper","model":"PS - 18D20 OD","description":"18' INCHES DUAL /2800W","type":"professional-subwoofer","category":"","subcategory":"KUA - OUTDOOR SUBWOOFERS","sort_order":570,"status":"active","prices":{"kasper":{"mrp":289990}}}
]$json$::jsonb) loop
    select p.id into v_id
    from public.products p join public.brands b on b.id = p.brand_id
    where b.slug = x->>'brand'
      and lower(regexp_replace(btrim(p.model_number), norm, ' ', 'g'))
        = lower(regexp_replace(btrim(x->>'model'), norm, ' ', 'g'));

    if v_id is null then
      select id into v_type from public.categories where slug = x->>'type';
      if v_type is null then raise exception 'Unknown product type "%" for %', x->>'type', x->>'model'; end if;
      perform public.price_save_product((x - 'type') || jsonb_build_object('type_id', v_type));
      n_new := n_new + 1;
    else
      perform public.price_save_product((x - 'type') || jsonb_build_object('id', v_id));
      n_upd := n_upd + 1;
    end if;
  end loop;

  raise notice 'price import: % updated, % inserted', n_upd, n_new;
end
$import$;

-- Regenerate slugs for every product the import touched.
update public.products p
set slug = public.price_slugify(b.slug || '-' || p.model_number)
from public.brands b
where b.id = p.brand_id and b.slug in ('stonewater-audio', 'kasper')
  and p.price_group_id is not null
  and p.slug is distinct from public.price_slugify(b.slug || '-' || p.model_number);

-- D1000 is not in the Excel sheet. Only deleted while it has no SKUs.
delete from public.products p
using public.brands b
where b.id = p.brand_id and b.slug = 'stonewater-audio' and p.model_number = 'D1000'
  and not exists (select 1 from public.variants v where v.product_id = p.id);

commit;
