/* build-catalog.mjs
 * Runs as part of the Netlify build (see netlify.toml). Reads every price from
 * Supabase ONCE per deploy and writes:
 *
 *   site/prices.json                     public, customer prices only, served
 *                                        from the CDN to every visitor
 *   netlify/generated/catalog-full.mjs   every price (dealer, distributor,
 *                                        margins), bundled INTO the
 *                                        prices-full function, never published
 *
 * So viewing the app never touches Supabase. To push new prices live, the
 * admin screen's Publish button triggers a rebuild (build hook).
 *
 * If Supabase can't be read the build fails, and Netlify keeps serving the
 * previous deploy, so the app never goes down because of a bad build.
 *
 * Local run: SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... node scripts/build-catalog.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { supabaseAdmin, selectAll, buildCatalog, publicCatalog, BRANDS } from "../netlify/lib/catalog.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const rows = await selectAll(supabaseAdmin(), "price_catalog", ["product_id", "list_id"]);
const full = { generatedAt: new Date().toISOString(), ...buildCatalog(rows) };

// Refuse to publish an empty or half-empty catalogue (e.g. a wrong key that
// returns no rows): failing the build keeps the last good deploy live.
for (const b of BRANDS) {
  const n = full.brands.find((x) => x.id === b.id).lists
    .flatMap((L) => L.categories.flatMap((c) => c.subcategories.flatMap((s) => s.products))).length;
  if (n === 0) {
    console.error(`build-catalog: no products for ${b.name}; refusing to publish an empty catalogue`);
    process.exit(1);
  }
}

const pub = publicCatalog(full);
writeFileSync(join(root, "site", "prices.json"), JSON.stringify(pub));
mkdirSync(join(root, "netlify", "generated"), { recursive: true });
writeFileSync(join(root, "netlify", "generated", "catalog-full.mjs"),
  "// Generated by scripts/build-catalog.mjs at build time. Do not edit or commit.\n" +
  "export default " + JSON.stringify(full) + ";\n");

const count = (c) => c.brands.map((b) => `${b.name}: ` + b.lists.map((L) =>
  `${L.label} ${L.categories.reduce((a, k) => a + k.subcategories.reduce((x, s) => x + s.products.length, 0), 0)}`).join(", ")).join(" | ");
console.log(`build-catalog: ${rows.length} price rows at ${full.generatedAt}`);
console.log(`build-catalog: public  -> ${count(pub)}`);
console.log(`build-catalog: full    -> ${count(full)}`);
